<?php
$this->headTitle()->set('About');
?>

<div class="modal hide fade about-dialog">
    <div class="modal-header">
        <div class="clearfix">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
    </div>
    <div class="modal-body">
        <div class="brand">
            <img class="pad2" src="<?php echo $this->escapeFullUrl($this->basePath()) ?>/swarm/img/logo-lg.png"
                width="119" height="135" alt="<?php echo $this->te('Perforce Swarm')?>"/>

            <h2><?php echo $this->te('Perforce Swarm')?></h2>
        </div>
        <div class="version muted">
            <?php echo $this->escapeHtml($version) ?>
        </div>
        <div class="copyright muted">
            <?php echo $this->te('Copyright') ?> &copy; <?php echo $this->escapeHtml($year) ?> <a href="http://www.perforce.com" target="_blank"><?php echo $this->te('Perforce Software')?></a>
        </div>
        <?php if ($this->permissions()->is('super')): ?>
        <div class="tokens">
            <strong><?php echo $this->tpe('Trigger Token', 'Trigger Tokens', count($tokens))?></strong><br>
            <?php foreach ($tokens as $token): ?>
                <input class="token muted center" readonly="readonly" value="<?php echo $this->escapeHtmlAttr($token) ?>"><br>
            <?php endforeach ?>
        </div>
        <?php endif ?>
        <?php if ($canAccessInfo): ?>
        <div class="system-info">
          <a href="<?php echo $this->url('info') ?>" target="_blank"><?php echo $this->te('System Information')?></a>
        </div>
        <?php endif ?>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        swarm.modal.show('.about-dialog');
    });
</script>
